import { Manrope } from 'next/font/google'
import './globals.css'

const manrope = Manrope({
   weight: '800',
   subsets: ['latin']
   })

export const metadata = {
  title: 'Advice Generator',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={manrope.className}>{children}</body>
    </html>
  )
}
